id: f2901553eb8244faa8da8ab2134a329c
initial_creation_type: ocr
source_metadata:
  volumes:
    af8634a42f454c9b9e6cebd8cee934e2:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ཡང་དག་ལྟ་བའི་སྒྲོན་མ།
      total_pages: 1902
      volume_number: 26
